export const mockBookListApi = [
  {
    key: '1',
    title: 'Book 1',
    author_name: ['Author 1'],
    cover_i: 1,
    first_publish_year: 1998,
  },
  {
    key: '2',
    title: 'Book 2',
    author_name: ['Author 2'],
    cover_i: 2,
    first_publish_year: 2002,
  },
  {
    key: '3',
    title: 'Book 3',
    author_name: ['Author 3'],
    cover_i: 2,
    first_publish_year: 2002,
  },
  {
    key: '4',
    title: 'Book 4',
    author_name: ['Author 4'],
    cover_i: 2,
    first_publish_year: 2002,
  },
  {
    key: '5',
    title: 'Book 5',
    author_name: ['Author 5'],
    cover_i: 2,
    first_publish_year: 2002,
  },
  {
    key: '6',
    title: 'Book 6',
    author_name: ['Author 6'],
    cover_i: 2,
    first_publish_year: 2002,
  },
  {
    key: '7',
    title: 'Book 7',
    author_name: ['Author 7'],
    cover_i: 2,
    first_publish_year: 2002,
  },
  {
    key: '8',
    title: 'Book 8',
    author_name: ['Author 8'],
    cover_i: 2,
    first_publish_year: 2002,
  },
  {
    key: '9',
    title: 'Book 9',
    author_name: ['Author 9'],
    cover_i: 2,
    first_publish_year: 2002,
  },
  {
    key: '10',
    title: 'Book 10',
    author_name: ['Author 10'],
    cover_i: 2,
    first_publish_year: 2002,
  },
];

export const mockBookList = [
  {
    key: '1',
    title: 'Book 1',
    author: 'Author 1',
    cover: 'https://covers.openlibrary.org/b/id/1.jpg',
    publishYear: 1998,
  },
  {
    key: '2',
    title: 'Book 2',
    author: 'Author 2',
    cover: 'https://covers.openlibrary.org/b/id/2.jpg',
    publishYear: 1998,
  },
  {
    key: '3',
    title: 'Book 3',
    author: 'Author 3',
    cover: 'https://covers.openlibrary.org/b/id/3.jpg',
    publishYear: 1998,
  },
  {
    key: '4',
    title: 'Book 4',
    author: 'Author 4',
    cover: 'https://covers.openlibrary.org/b/id/4.jpg',
    publishYear: 1998,
  },
  {
    key: '5',
    title: 'Book 5',
    author: 'Author 5',
    cover: 'https://covers.openlibrary.org/b/id/5.jpg',
    publishYear: 1998,
  },
];
